-- 예상 시간복잡도: O(NlogN)
SELECT PRODUCT.PRODUCT_CODE, SUM(OFFLINE_SALE.SALES_AMOUNT)*PRODUCT.PRICE AS TOTAL FROM OFFLINE_SALE
JOIN PRODUCT ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY OFFLINE_SALE.PRODUCT_ID
ORDER BY TOTAL desc, PRODUCT.PRODUCT_CODE;
