-- 예상 시간복잡도: O(NlogN)
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') FROM MEMBER_PROFILE
WHERE DATE_OF_BIRTH LIKE '%-03-%' AND GENDER = 'W' AND TLNO is not NULL
ORDER BY MEMBER_ID;
