-- 예상 시간복잡도: O(NlogN)
SELECT CAR_ID, ROUND(AVG(1+DATEDIFF(END_DATE, START_DATE)),1) AS AVERAGE_DURATION FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID HAVING AVERAGE_DURATION>=7
ORDER BY AVERAGE_DURATION desc, CAR_ID desc;
